// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: proto/prime.proto

package primepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PrimeWorker_ProcessChunk_FullMethodName = "/primepb.PrimeWorker/ProcessChunk"
)

// PrimeWorkerClient is the client API for PrimeWorker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PrimeWorkerClient interface {
	// The Coordinator sends a WorkChunk, the Worker processes it and returns a PrimeResult.
	ProcessChunk(ctx context.Context, in *WorkChunk, opts ...grpc.CallOption) (*PrimeResult, error)
}

type primeWorkerClient struct {
	cc grpc.ClientConnInterface
}

func NewPrimeWorkerClient(cc grpc.ClientConnInterface) PrimeWorkerClient {
	return &primeWorkerClient{cc}
}

func (c *primeWorkerClient) ProcessChunk(ctx context.Context, in *WorkChunk, opts ...grpc.CallOption) (*PrimeResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrimeResult)
	err := c.cc.Invoke(ctx, PrimeWorker_ProcessChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PrimeWorkerServer is the server API for PrimeWorker service.
// All implementations must embed UnimplementedPrimeWorkerServer
// for forward compatibility.
type PrimeWorkerServer interface {
	// The Coordinator sends a WorkChunk, the Worker processes it and returns a PrimeResult.
	ProcessChunk(context.Context, *WorkChunk) (*PrimeResult, error)
	mustEmbedUnimplementedPrimeWorkerServer()
}

// UnimplementedPrimeWorkerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPrimeWorkerServer struct{}

func (UnimplementedPrimeWorkerServer) ProcessChunk(context.Context, *WorkChunk) (*PrimeResult, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessChunk not implemented")
}
func (UnimplementedPrimeWorkerServer) mustEmbedUnimplementedPrimeWorkerServer() {}
func (UnimplementedPrimeWorkerServer) testEmbeddedByValue()                     {}

// UnsafePrimeWorkerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PrimeWorkerServer will
// result in compilation errors.
type UnsafePrimeWorkerServer interface {
	mustEmbedUnimplementedPrimeWorkerServer()
}

func RegisterPrimeWorkerServer(s grpc.ServiceRegistrar, srv PrimeWorkerServer) {
	// If the following call panics, it indicates UnimplementedPrimeWorkerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PrimeWorker_ServiceDesc, srv)
}

func _PrimeWorker_ProcessChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkChunk)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrimeWorkerServer).ProcessChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrimeWorker_ProcessChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrimeWorkerServer).ProcessChunk(ctx, req.(*WorkChunk))
	}
	return interceptor(ctx, in, info, handler)
}

// PrimeWorker_ServiceDesc is the grpc.ServiceDesc for PrimeWorker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PrimeWorker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "primepb.PrimeWorker",
	HandlerType: (*PrimeWorkerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessChunk",
			Handler:    _PrimeWorker_ProcessChunk_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/prime.proto",
}
