// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/afs.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Version       int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestAuthRequest) Reset() {
	*x = TestAuthRequest{}
	mi := &file_proto_afs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestAuthRequest) ProtoMessage() {}

func (x *TestAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_afs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestAuthRequest.ProtoReflect.Descriptor instead.
func (*TestAuthRequest) Descriptor() ([]byte, []int) {
	return file_proto_afs_proto_rawDescGZIP(), []int{0}
}

func (x *TestAuthRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *TestAuthRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type TestAuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsValid       bool                   `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	ServerVersion int32                  `protobuf:"varint,2,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestAuthResponse) Reset() {
	*x = TestAuthResponse{}
	mi := &file_proto_afs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestAuthResponse) ProtoMessage() {}

func (x *TestAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_afs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestAuthResponse.ProtoReflect.Descriptor instead.
func (*TestAuthResponse) Descriptor() ([]byte, []int) {
	return file_proto_afs_proto_rawDescGZIP(), []int{1}
}

func (x *TestAuthResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *TestAuthResponse) GetServerVersion() int32 {
	if x != nil {
		return x.ServerVersion
	}
	return 0
}

type FileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileRequest) Reset() {
	*x = FileRequest{}
	mi := &file_proto_afs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRequest) ProtoMessage() {}

func (x *FileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_afs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRequest.ProtoReflect.Descriptor instead.
func (*FileRequest) Descriptor() ([]byte, []int) {
	return file_proto_afs_proto_rawDescGZIP(), []int{2}
}

func (x *FileRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type FileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Version       int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_proto_afs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_afs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_proto_afs_proto_rawDescGZIP(), []int{3}
}

func (x *FileChunk) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *FileChunk) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type StoreChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreChunk) Reset() {
	*x = StoreChunk{}
	mi := &file_proto_afs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreChunk) ProtoMessage() {}

func (x *StoreChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_afs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreChunk.ProtoReflect.Descriptor instead.
func (*StoreChunk) Descriptor() ([]byte, []int) {
	return file_proto_afs_proto_rawDescGZIP(), []int{4}
}

func (x *StoreChunk) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *StoreChunk) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type StoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	NewVersion    int32                  `protobuf:"varint,2,opt,name=new_version,json=newVersion,proto3" json:"new_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreResponse) Reset() {
	*x = StoreResponse{}
	mi := &file_proto_afs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreResponse) ProtoMessage() {}

func (x *StoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_afs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreResponse.ProtoReflect.Descriptor instead.
func (*StoreResponse) Descriptor() ([]byte, []int) {
	return file_proto_afs_proto_rawDescGZIP(), []int{5}
}

func (x *StoreResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StoreResponse) GetNewVersion() int32 {
	if x != nil {
		return x.NewVersion
	}
	return 0
}

var File_proto_afs_proto protoreflect.FileDescriptor

const file_proto_afs_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/afs.proto\x12\x03afs\"G\n" +
	"\x0fTestAuthRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\"T\n" +
	"\x10TestAuthResponse\x12\x19\n" +
	"\bis_valid\x18\x01 \x01(\bR\aisValid\x12%\n" +
	"\x0eserver_version\x18\x02 \x01(\x05R\rserverVersion\")\n" +
	"\vFileRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\"?\n" +
	"\tFileChunk\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\"B\n" +
	"\n" +
	"StoreChunk\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\"J\n" +
	"\rStoreResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vnew_version\x18\x02 \x01(\x05R\n" +
	"newVersion2\xa3\x01\n" +
	"\x03AFS\x127\n" +
	"\bTestAuth\x12\x14.afs.TestAuthRequest\x1a\x15.afs.TestAuthResponse\x12/\n" +
	"\tFetchFile\x12\x10.afs.FileRequest\x1a\x0e.afs.FileChunk0\x01\x122\n" +
	"\tStoreFile\x12\x0f.afs.StoreChunk\x1a\x12.afs.StoreResponse(\x01B\x12Z\x10primality_afs/pbb\x06proto3"

var (
	file_proto_afs_proto_rawDescOnce sync.Once
	file_proto_afs_proto_rawDescData []byte
)

func file_proto_afs_proto_rawDescGZIP() []byte {
	file_proto_afs_proto_rawDescOnce.Do(func() {
		file_proto_afs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_afs_proto_rawDesc), len(file_proto_afs_proto_rawDesc)))
	})
	return file_proto_afs_proto_rawDescData
}

var file_proto_afs_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_afs_proto_goTypes = []any{
	(*TestAuthRequest)(nil),  // 0: afs.TestAuthRequest
	(*TestAuthResponse)(nil), // 1: afs.TestAuthResponse
	(*FileRequest)(nil),      // 2: afs.FileRequest
	(*FileChunk)(nil),        // 3: afs.FileChunk
	(*StoreChunk)(nil),       // 4: afs.StoreChunk
	(*StoreResponse)(nil),    // 5: afs.StoreResponse
}
var file_proto_afs_proto_depIdxs = []int32{
	0, // 0: afs.AFS.TestAuth:input_type -> afs.TestAuthRequest
	2, // 1: afs.AFS.FetchFile:input_type -> afs.FileRequest
	4, // 2: afs.AFS.StoreFile:input_type -> afs.StoreChunk
	1, // 3: afs.AFS.TestAuth:output_type -> afs.TestAuthResponse
	3, // 4: afs.AFS.FetchFile:output_type -> afs.FileChunk
	5, // 5: afs.AFS.StoreFile:output_type -> afs.StoreResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_afs_proto_init() }
func file_proto_afs_proto_init() {
	if File_proto_afs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_afs_proto_rawDesc), len(file_proto_afs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_afs_proto_goTypes,
		DependencyIndexes: file_proto_afs_proto_depIdxs,
		MessageInfos:      file_proto_afs_proto_msgTypes,
	}.Build()
	File_proto_afs_proto = out.File
	file_proto_afs_proto_goTypes = nil
	file_proto_afs_proto_depIdxs = nil
}
