// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: proto/afs.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AFS_TestAuth_FullMethodName  = "/afs.AFS/TestAuth"
	AFS_FetchFile_FullMethodName = "/afs.AFS/FetchFile"
	AFS_StoreFile_FullMethodName = "/afs.AFS/StoreFile"
)

// AFSClient is the client API for AFS service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AFSClient interface {
	TestAuth(ctx context.Context, in *TestAuthRequest, opts ...grpc.CallOption) (*TestAuthResponse, error)
	FetchFile(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileChunk], error)
	StoreFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[StoreChunk, StoreResponse], error)
}

type aFSClient struct {
	cc grpc.ClientConnInterface
}

func NewAFSClient(cc grpc.ClientConnInterface) AFSClient {
	return &aFSClient{cc}
}

func (c *aFSClient) TestAuth(ctx context.Context, in *TestAuthRequest, opts ...grpc.CallOption) (*TestAuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestAuthResponse)
	err := c.cc.Invoke(ctx, AFS_TestAuth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aFSClient) FetchFile(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AFS_ServiceDesc.Streams[0], AFS_FetchFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FileRequest, FileChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AFS_FetchFileClient = grpc.ServerStreamingClient[FileChunk]

func (c *aFSClient) StoreFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[StoreChunk, StoreResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AFS_ServiceDesc.Streams[1], AFS_StoreFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StoreChunk, StoreResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AFS_StoreFileClient = grpc.ClientStreamingClient[StoreChunk, StoreResponse]

// AFSServer is the server API for AFS service.
// All implementations must embed UnimplementedAFSServer
// for forward compatibility.
type AFSServer interface {
	TestAuth(context.Context, *TestAuthRequest) (*TestAuthResponse, error)
	FetchFile(*FileRequest, grpc.ServerStreamingServer[FileChunk]) error
	StoreFile(grpc.ClientStreamingServer[StoreChunk, StoreResponse]) error
	mustEmbedUnimplementedAFSServer()
}

// UnimplementedAFSServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAFSServer struct{}

func (UnimplementedAFSServer) TestAuth(context.Context, *TestAuthRequest) (*TestAuthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TestAuth not implemented")
}
func (UnimplementedAFSServer) FetchFile(*FileRequest, grpc.ServerStreamingServer[FileChunk]) error {
	return status.Error(codes.Unimplemented, "method FetchFile not implemented")
}
func (UnimplementedAFSServer) StoreFile(grpc.ClientStreamingServer[StoreChunk, StoreResponse]) error {
	return status.Error(codes.Unimplemented, "method StoreFile not implemented")
}
func (UnimplementedAFSServer) mustEmbedUnimplementedAFSServer() {}
func (UnimplementedAFSServer) testEmbeddedByValue()             {}

// UnsafeAFSServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AFSServer will
// result in compilation errors.
type UnsafeAFSServer interface {
	mustEmbedUnimplementedAFSServer()
}

func RegisterAFSServer(s grpc.ServiceRegistrar, srv AFSServer) {
	// If the following call panics, it indicates UnimplementedAFSServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AFS_ServiceDesc, srv)
}

func _AFS_TestAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AFSServer).TestAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AFS_TestAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AFSServer).TestAuth(ctx, req.(*TestAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AFS_FetchFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AFSServer).FetchFile(m, &grpc.GenericServerStream[FileRequest, FileChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AFS_FetchFileServer = grpc.ServerStreamingServer[FileChunk]

func _AFS_StoreFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AFSServer).StoreFile(&grpc.GenericServerStream[StoreChunk, StoreResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AFS_StoreFileServer = grpc.ClientStreamingServer[StoreChunk, StoreResponse]

// AFS_ServiceDesc is the grpc.ServiceDesc for AFS service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AFS_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "afs.AFS",
	HandlerType: (*AFSServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TestAuth",
			Handler:    _AFS_TestAuth_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "FetchFile",
			Handler:       _AFS_FetchFile_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StoreFile",
			Handler:       _AFS_StoreFile_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/afs.proto",
}
